// Generated by gencpp from file simple_s/Num.msg
// DO NOT EDIT!


#ifndef SIMPLE_S_MESSAGE_NUM_H
#define SIMPLE_S_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simple_s
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : content()
    , id(0)
    , timestamp(0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : content(_alloc)
    , id(0)
    , timestamp(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _content_type;
  _content_type content;

   typedef int64_t _id_type;
  _id_type id;

   typedef int64_t _timestamp_type;
  _timestamp_type timestamp;





  typedef boost::shared_ptr< ::simple_s::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simple_s::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::simple_s::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::simple_s::Num > NumPtr;
typedef boost::shared_ptr< ::simple_s::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simple_s::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simple_s::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simple_s

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'simple_s': ['/ros_test/AD_Middle_Test/ros/src/simple_s/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simple_s::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_s::Num_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_s::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_s::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_s::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_s::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simple_s::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34f0a63c6019bc102c58640902c234e7";
  }

  static const char* value(const ::simple_s::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34f0a63c6019bc10ULL;
  static const uint64_t static_value2 = 0x2c58640902c234e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::simple_s::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simple_s/Num";
  }

  static const char* value(const ::simple_s::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simple_s::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string content\n"
"int64 id\n"
"int64 timestamp\n"
;
  }

  static const char* value(const ::simple_s::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simple_s::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.content);
      stream.next(m.id);
      stream.next(m.timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simple_s::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simple_s::Num_<ContainerAllocator>& v)
  {
    s << indent << "content: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.content);
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
    s << indent << "timestamp: ";
    Printer<int64_t>::stream(s, indent + "  ", v.timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMPLE_S_MESSAGE_NUM_H
