tcpS:tcpServer.cpp
	g++ $^ -o $@ -std=c++11
tcpC:tcpClient.cpp
	g++ $^ -o $@ -std=c++11

udpS:udpServer.cpp
	g++ $^ -o $@ -std=c++11

udpC:udpClient.cpp
	g++ $^ -o $@ -std=c++11

all : tcpS tcpC udpS udpC
