// Generated by gencpp from file detect_s/FusionResult.msg
// DO NOT EDIT!


#ifndef DETECT_S_MESSAGE_FUSIONRESULT_H
#define DETECT_S_MESSAGE_FUSIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace detect_s
{
template <class ContainerAllocator>
struct FusionResult_
{
  typedef FusionResult_<ContainerAllocator> Type;

  FusionResult_()
    : header()
    , fusion_result()  {
    }
  FusionResult_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , fusion_result(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _fusion_result_type;
  _fusion_result_type fusion_result;





  typedef boost::shared_ptr< ::detect_s::FusionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detect_s::FusionResult_<ContainerAllocator> const> ConstPtr;

}; // struct FusionResult_

typedef ::detect_s::FusionResult_<std::allocator<void> > FusionResult;

typedef boost::shared_ptr< ::detect_s::FusionResult > FusionResultPtr;
typedef boost::shared_ptr< ::detect_s::FusionResult const> FusionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detect_s::FusionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detect_s::FusionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace detect_s

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'detect_s': ['/ros_test/AD_Middle_Test/ros/src/detect_s/msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::detect_s::FusionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detect_s::FusionResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_s::FusionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_s::FusionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_s::FusionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_s::FusionResult_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detect_s::FusionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13ab230e8044806d1305c415579c8329";
  }

  static const char* value(const ::detect_s::FusionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13ab230e8044806dULL;
  static const uint64_t static_value2 = 0x1305c415579c8329ULL;
};

template<class ContainerAllocator>
struct DataType< ::detect_s::FusionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detect_s/FusionResult";
  }

  static const char* value(const ::detect_s::FusionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detect_s::FusionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"string fusion_result\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::detect_s::FusionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detect_s::FusionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.fusion_result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FusionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detect_s::FusionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detect_s::FusionResult_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "fusion_result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.fusion_result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECT_S_MESSAGE_FUSIONRESULT_H
