// Generated by gencpp from file detect_s/TrackerResult.msg
// DO NOT EDIT!


#ifndef DETECT_S_MESSAGE_TRACKERRESULT_H
#define DETECT_S_MESSAGE_TRACKERRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detect_s
{
template <class ContainerAllocator>
struct TrackerResult_
{
  typedef TrackerResult_<ContainerAllocator> Type;

  TrackerResult_()
    : x(0.0)
    , y(0.0)
    , width(0.0)
    , height(0.0)  {
    }
  TrackerResult_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , width(0.0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _width_type;
  _width_type width;

   typedef double _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::detect_s::TrackerResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detect_s::TrackerResult_<ContainerAllocator> const> ConstPtr;

}; // struct TrackerResult_

typedef ::detect_s::TrackerResult_<std::allocator<void> > TrackerResult;

typedef boost::shared_ptr< ::detect_s::TrackerResult > TrackerResultPtr;
typedef boost::shared_ptr< ::detect_s::TrackerResult const> TrackerResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detect_s::TrackerResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detect_s::TrackerResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace detect_s

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'detect_s': ['/ros_test/AD_Middle_Test/ros/src/detect_s/msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::detect_s::TrackerResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detect_s::TrackerResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_s::TrackerResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_s::TrackerResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_s::TrackerResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_s::TrackerResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detect_s::TrackerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7048f28f1f0ef51e102638c86d9a7728";
  }

  static const char* value(const ::detect_s::TrackerResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7048f28f1f0ef51eULL;
  static const uint64_t static_value2 = 0x102638c86d9a7728ULL;
};

template<class ContainerAllocator>
struct DataType< ::detect_s::TrackerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detect_s/TrackerResult";
  }

  static const char* value(const ::detect_s::TrackerResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detect_s::TrackerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 width\n"
"float64 height\n"
;
  }

  static const char* value(const ::detect_s::TrackerResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detect_s::TrackerResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrackerResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detect_s::TrackerResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detect_s::TrackerResult_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "width: ";
    Printer<double>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECT_S_MESSAGE_TRACKERRESULT_H
