// Generated by gencpp from file detect_s/YoloResult.msg
// DO NOT EDIT!


#ifndef DETECT_S_MESSAGE_YOLORESULT_H
#define DETECT_S_MESSAGE_YOLORESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <detect_s/YoloPiece.h>

namespace detect_s
{
template <class ContainerAllocator>
struct YoloResult_
{
  typedef YoloResult_<ContainerAllocator> Type;

  YoloResult_()
    : header()
    , result_num(0)
    , result_array()  {
    }
  YoloResult_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , result_num(0)
    , result_array(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _result_num_type;
  _result_num_type result_num;

   typedef std::vector< ::detect_s::YoloPiece_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::detect_s::YoloPiece_<ContainerAllocator> >::other >  _result_array_type;
  _result_array_type result_array;





  typedef boost::shared_ptr< ::detect_s::YoloResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detect_s::YoloResult_<ContainerAllocator> const> ConstPtr;

}; // struct YoloResult_

typedef ::detect_s::YoloResult_<std::allocator<void> > YoloResult;

typedef boost::shared_ptr< ::detect_s::YoloResult > YoloResultPtr;
typedef boost::shared_ptr< ::detect_s::YoloResult const> YoloResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detect_s::YoloResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detect_s::YoloResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace detect_s

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'detect_s': ['/ros_test/AD_Middle_Test/ros/src/detect_s/msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::detect_s::YoloResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detect_s::YoloResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_s::YoloResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detect_s::YoloResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_s::YoloResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detect_s::YoloResult_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detect_s::YoloResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "025cd73ca927f284ee50b77a0569f132";
  }

  static const char* value(const ::detect_s::YoloResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x025cd73ca927f284ULL;
  static const uint64_t static_value2 = 0xee50b77a0569f132ULL;
};

template<class ContainerAllocator>
struct DataType< ::detect_s::YoloResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detect_s/YoloResult";
  }

  static const char* value(const ::detect_s::YoloResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detect_s::YoloResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint32 result_num\n"
"YoloPiece[] result_array\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: detect_s/YoloPiece\n"
"uint32 x\n"
"uint32 y\n"
"uint32 w\n"
"uint32 h\n"
"float32 prob\n"
"float32 obj_id\n"
"float32 track_id\n"
"float32 frames_counter\n"
;
  }

  static const char* value(const ::detect_s::YoloResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detect_s::YoloResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.result_num);
      stream.next(m.result_array);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YoloResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detect_s::YoloResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detect_s::YoloResult_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "result_num: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.result_num);
    s << indent << "result_array[]" << std::endl;
    for (size_t i = 0; i < v.result_array.size(); ++i)
    {
      s << indent << "  result_array[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::detect_s::YoloPiece_<ContainerAllocator> >::stream(s, indent + "    ", v.result_array[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECT_S_MESSAGE_YOLORESULT_H
