# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from detect_s/LinesResult.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import detect_s.msg
import std_msgs.msg

class LinesResult(genpy.Message):
  _md5sum = "450c7b7554f64d28c44fff48a609a687"
  _type = "detect_s/LinesResult"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
PointDetect left1
PointDetect right1
PointDetect left2
PointDetect right2

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: detect_s/PointDetect
int32 x
int32 y
"""
  __slots__ = ['header','left1','right1','left2','right2']
  _slot_types = ['std_msgs/Header','detect_s/PointDetect','detect_s/PointDetect','detect_s/PointDetect','detect_s/PointDetect']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,left1,right1,left2,right2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LinesResult, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left1 is None:
        self.left1 = detect_s.msg.PointDetect()
      if self.right1 is None:
        self.right1 = detect_s.msg.PointDetect()
      if self.left2 is None:
        self.left2 = detect_s.msg.PointDetect()
      if self.right2 is None:
        self.right2 = detect_s.msg.PointDetect()
    else:
      self.header = std_msgs.msg.Header()
      self.left1 = detect_s.msg.PointDetect()
      self.right1 = detect_s.msg.PointDetect()
      self.left2 = detect_s.msg.PointDetect()
      self.right2 = detect_s.msg.PointDetect()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_8i().pack(_x.left1.x, _x.left1.y, _x.right1.x, _x.right1.y, _x.left2.x, _x.left2.y, _x.right2.x, _x.right2.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left1 is None:
        self.left1 = detect_s.msg.PointDetect()
      if self.right1 is None:
        self.right1 = detect_s.msg.PointDetect()
      if self.left2 is None:
        self.left2 = detect_s.msg.PointDetect()
      if self.right2 is None:
        self.right2 = detect_s.msg.PointDetect()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.left1.x, _x.left1.y, _x.right1.x, _x.right1.y, _x.left2.x, _x.left2.y, _x.right2.x, _x.right2.y,) = _get_struct_8i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_8i().pack(_x.left1.x, _x.left1.y, _x.right1.x, _x.right1.y, _x.left2.x, _x.left2.y, _x.right2.x, _x.right2.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.left1 is None:
        self.left1 = detect_s.msg.PointDetect()
      if self.right1 is None:
        self.right1 = detect_s.msg.PointDetect()
      if self.left2 is None:
        self.left2 = detect_s.msg.PointDetect()
      if self.right2 is None:
        self.right2 = detect_s.msg.PointDetect()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.left1.x, _x.left1.y, _x.right1.x, _x.right1.y, _x.left2.x, _x.left2.y, _x.right2.x, _x.right2.y,) = _get_struct_8i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_8i = None
def _get_struct_8i():
    global _struct_8i
    if _struct_8i is None:
        _struct_8i = struct.Struct("<8i")
    return _struct_8i
