# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from detect_s/LinesResult.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import detect_s.msg

class LinesResult(genpy.Message):
  _md5sum = "31748639f016450bce732dc22ce90507"
  _type = "detect_s/LinesResult"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """PointDetect left1
PointDetect right1
PointDetect left2
PointDetect right2

================================================================================
MSG: detect_s/PointDetect
int32 x
int32 y
"""
  __slots__ = ['left1','right1','left2','right2']
  _slot_types = ['detect_s/PointDetect','detect_s/PointDetect','detect_s/PointDetect','detect_s/PointDetect']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left1,right1,left2,right2

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LinesResult, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.left1 is None:
        self.left1 = detect_s.msg.PointDetect()
      if self.right1 is None:
        self.right1 = detect_s.msg.PointDetect()
      if self.left2 is None:
        self.left2 = detect_s.msg.PointDetect()
      if self.right2 is None:
        self.right2 = detect_s.msg.PointDetect()
    else:
      self.left1 = detect_s.msg.PointDetect()
      self.right1 = detect_s.msg.PointDetect()
      self.left2 = detect_s.msg.PointDetect()
      self.right2 = detect_s.msg.PointDetect()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8i().pack(_x.left1.x, _x.left1.y, _x.right1.x, _x.right1.y, _x.left2.x, _x.left2.y, _x.right2.x, _x.right2.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.left1 is None:
        self.left1 = detect_s.msg.PointDetect()
      if self.right1 is None:
        self.right1 = detect_s.msg.PointDetect()
      if self.left2 is None:
        self.left2 = detect_s.msg.PointDetect()
      if self.right2 is None:
        self.right2 = detect_s.msg.PointDetect()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.left1.x, _x.left1.y, _x.right1.x, _x.right1.y, _x.left2.x, _x.left2.y, _x.right2.x, _x.right2.y,) = _get_struct_8i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8i().pack(_x.left1.x, _x.left1.y, _x.right1.x, _x.right1.y, _x.left2.x, _x.left2.y, _x.right2.x, _x.right2.y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.left1 is None:
        self.left1 = detect_s.msg.PointDetect()
      if self.right1 is None:
        self.right1 = detect_s.msg.PointDetect()
      if self.left2 is None:
        self.left2 = detect_s.msg.PointDetect()
      if self.right2 is None:
        self.right2 = detect_s.msg.PointDetect()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.left1.x, _x.left1.y, _x.right1.x, _x.right1.y, _x.left2.x, _x.left2.y, _x.right2.x, _x.right2.y,) = _get_struct_8i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8i = None
def _get_struct_8i():
    global _struct_8i
    if _struct_8i is None:
        _struct_8i = struct.Struct("<8i")
    return _struct_8i
